# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Sat Feb  1 23:20:33 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1020, 400)
        self.lineEdit_file_path = QtGui.QLineEdit(Form)
        self.lineEdit_file_path.setGeometry(QtCore.QRect(30, 140, 301, 27))
        self.lineEdit_file_path.setObjectName(_fromUtf8("lineEdit_file_path"))
        self.pushButton_load_image = QtGui.QPushButton(Form)
        self.pushButton_load_image.setGeometry(QtCore.QRect(30, 170, 98, 27))
        self.pushButton_load_image.setObjectName(_fromUtf8("pushButton_load_image"))
        self.pushButton_send_image = QtGui.QPushButton(Form)
        self.pushButton_send_image.setGeometry(QtCore.QRect(230, 170, 98, 27))
        self.pushButton_send_image.setObjectName(_fromUtf8("pushButton_send_image"))
        self.pushButton_stream_webcam = QtGui.QPushButton(Form)
        self.pushButton_stream_webcam.setGeometry(QtCore.QRect(500, 300, 141, 71))
        self.pushButton_stream_webcam.setObjectName(_fromUtf8("pushButton_stream_webcam"))
        self.horizontalSlider_fps = QtGui.QSlider(Form)
        self.horizontalSlider_fps.setGeometry(QtCore.QRect(340, 350, 141, 29))
        self.horizontalSlider_fps.setMinimum(1)
        self.horizontalSlider_fps.setMaximum(1024)
        self.horizontalSlider_fps.setProperty("value", 25)
        self.horizontalSlider_fps.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_fps.setObjectName(_fromUtf8("horizontalSlider_fps"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(300, 310, 31, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lcdNumber = QtGui.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(350, 300, 131, 41))
        self.lcdNumber.setProperty("value", 25.0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.checkBox_equalize = QtGui.QCheckBox(Form)
        self.checkBox_equalize.setGeometry(QtCore.QRect(200, 350, 97, 22))
        self.checkBox_equalize.setObjectName(_fromUtf8("checkBox_equalize"))
        self.pushButton_browse = QtGui.QPushButton(Form)
        self.pushButton_browse.setGeometry(QtCore.QRect(350, 140, 98, 27))
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(500, 50, 491, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalSlider_red = QtGui.QSlider(self.groupBox)
        self.verticalSlider_red.setGeometry(QtCore.QRect(140, 20, 20, 111))
        self.verticalSlider_red.setMaximum(100)
        self.verticalSlider_red.setSliderPosition(100)
        self.verticalSlider_red.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_red.setObjectName(_fromUtf8("verticalSlider_red"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(140, 170, 31, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(190, 170, 41, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(260, 170, 31, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(430, 170, 51, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lcdNumber_red = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_red.setGeometry(QtCore.QRect(130, 140, 41, 31))
        self.lcdNumber_red.setNumDigits(3)
        self.lcdNumber_red.setProperty("value", 100.0)
        self.lcdNumber_red.setObjectName(_fromUtf8("lcdNumber_red"))
        self.lcdNumber_green = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_green.setGeometry(QtCore.QRect(190, 140, 41, 31))
        self.lcdNumber_green.setNumDigits(3)
        self.lcdNumber_green.setProperty("value", 100.0)
        self.lcdNumber_green.setObjectName(_fromUtf8("lcdNumber_green"))
        self.lcdNumber_blue = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_blue.setGeometry(QtCore.QRect(250, 140, 41, 31))
        self.lcdNumber_blue.setNumDigits(3)
        self.lcdNumber_blue.setProperty("value", 100.0)
        self.lcdNumber_blue.setObjectName(_fromUtf8("lcdNumber_blue"))
        self.verticalSlider_gamma = QtGui.QSlider(self.groupBox)
        self.verticalSlider_gamma.setGeometry(QtCore.QRect(440, 20, 20, 111))
        self.verticalSlider_gamma.setMaximum(400)
        self.verticalSlider_gamma.setProperty("value", 200)
        self.verticalSlider_gamma.setSliderPosition(200)
        self.verticalSlider_gamma.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_gamma.setObjectName(_fromUtf8("verticalSlider_gamma"))
        self.verticalSlider_green = QtGui.QSlider(self.groupBox)
        self.verticalSlider_green.setGeometry(QtCore.QRect(200, 20, 20, 111))
        self.verticalSlider_green.setMaximum(100)
        self.verticalSlider_green.setSliderPosition(100)
        self.verticalSlider_green.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_green.setObjectName(_fromUtf8("verticalSlider_green"))
        self.verticalSlider_blue = QtGui.QSlider(self.groupBox)
        self.verticalSlider_blue.setGeometry(QtCore.QRect(260, 20, 20, 111))
        self.verticalSlider_blue.setMaximum(100)
        self.verticalSlider_blue.setProperty("value", 100)
        self.verticalSlider_blue.setSliderPosition(100)
        self.verticalSlider_blue.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_blue.setObjectName(_fromUtf8("verticalSlider_blue"))
        self.lcdNumber_gamma = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_gamma.setGeometry(QtCore.QRect(430, 140, 41, 31))
        self.lcdNumber_gamma.setNumDigits(3)
        self.lcdNumber_gamma.setProperty("value", 200.0)
        self.lcdNumber_gamma.setObjectName(_fromUtf8("lcdNumber_gamma"))
        self.verticalSlider_brightness = QtGui.QSlider(self.groupBox)
        self.verticalSlider_brightness.setGeometry(QtCore.QRect(330, 20, 20, 111))
        self.verticalSlider_brightness.setMaximum(100)
        self.verticalSlider_brightness.setProperty("value", 25)
        self.verticalSlider_brightness.setSliderPosition(25)
        self.verticalSlider_brightness.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_brightness.setObjectName(_fromUtf8("verticalSlider_brightness"))
        self.lcdNumber_brightness = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_brightness.setGeometry(QtCore.QRect(320, 140, 41, 31))
        self.lcdNumber_brightness.setNumDigits(3)
        self.lcdNumber_brightness.setProperty("value", 25.0)
        self.lcdNumber_brightness.setObjectName(_fromUtf8("lcdNumber_brightness"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(320, 170, 61, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.horizontalSlider_fps, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber.display)
        QtCore.QObject.connect(self.verticalSlider_red, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_red.display)
        QtCore.QObject.connect(self.verticalSlider_green, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_green.display)
        QtCore.QObject.connect(self.verticalSlider_blue, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_blue.display)
        QtCore.QObject.connect(self.verticalSlider_gamma, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_gamma.display)
        QtCore.QObject.connect(self.verticalSlider_brightness, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lcdNumber_brightness.display)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit_file_path.setText(_translate("Form", "/home/stephan/Pictures/mario.jpg", None))
        self.pushButton_load_image.setText(_translate("Form", "Bild laden", None))
        self.pushButton_send_image.setText(_translate("Form", "Bild senden", None))
        self.pushButton_stream_webcam.setText(_translate("Form", "Webcam streamen", None))
        self.label_4.setText(_translate("Form", "FPS", None))
        self.checkBox_equalize.setText(_translate("Form", "Equalize", None))
        self.pushButton_browse.setText(_translate("Form", "Durchsuchen", None))
        self.groupBox.setTitle(_translate("Form", "Farbkorrektur", None))
        self.label.setText(_translate("Form", "Red", None))
        self.label_2.setText(_translate("Form", "Green", None))
        self.label_3.setText(_translate("Form", "Blue", None))
        self.label_5.setText(_translate("Form", "Gamma", None))
        self.label_6.setText(_translate("Form", "Brightness", None))

